# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  init2:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  A:
    needs: [init, init2]
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, start1!
  B:
    needs: [init, init2]
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, start1!
  C:
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, start1!
  D:
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, start1!
  E:
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, start1!
  F:
    needs: [init2]
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, start1!
  G:
    needs: [init2]
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, start1!
  H:
    needs: [init2]
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, start1!
  J:
    needs: [init2]
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, start1!
  final:
    needs: [init, A, B]
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, final!
  final2:
    needs: [F]
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, final!
